### ISSUE TITLE
Public Roadmap and ideas.

### ISSUE THREAD

**Issue by Schmoopiie** [twitch-irc/twitch-irc#89]
The Roadmap aims to set out when certain features will appear. It reduces in clarity the further we go into the future, and is constantly being added to as we move forward.

**1.2.8**
- [ ] Better handling of graceful reconnection.
- [ ] Buy a domain name and host everything related to twitch-irc on it. (docs and forums)
- [ ] Create a forums.
- [ ] Deprecate uncaughtException once and for all.
- [ ] First message when using emitSelf not being sent. [#82](https://github.com/twitch-irc/twitch-irc/issues/82)
- [ ] Improve performance of IRCv3 tags by just reading and sending back to the user object.
- [ ] Include client id in header requests (if available) for twitch-irc-oauth. (Requested by Twitch Staff)
- [ ] Move this Roadmap to the forums.
- [ ] Remove unused code and try to improve existing one.

**1.3.X**
- [ ] Improve the logging feature. (Might use Winston with categories)
- [ ] Use ES6 new features as soon as they are available for Node.js ([Current state of ES6 with Node.js](https://kangax.github.io/compat-table/es6/#node))

**Comment by mccxiv** [comment]
:+1: And welcome back

**Comment by Schmoopiie** [comment]
Thank you! :smile:

**Comment by Schmoopiie** [comment]
Lot of changes from Twitch, we will need more time to release 1.2.8. You can still use the GitHub repository as the latest version of the module. Right now I am more focused on the forums and reading the new changes from Twitch.

**Comment by celluj34** [comment]
Have a link to any significant changes?

**Comment by Schmoopiie** [comment]
Most of the changes are announced on their [dev forums](http://discuss.dev.twitch.tv) but I always take the source code of twitch.tv and check the tmi.js file to see the upcoming changes :smile:

**Comment by SReject** [comment]
Schmoopii, have you thought of using io,js in place of node to take advantage of es6 features sooner?

**Comment by Schmoopiie** [comment]
A merge between io.js and node.js is on it's way and will be under a new entity called The Node Foundation. There are no plans to use ES6 features as long as the merge is not done. At this time, the module is compatible with io.js and node.js and if we add ES6 features, the module would be compatible with io.js only.
